# -*- coding: utf-8 -*-
"""Actividad Evaluable: Mapas de calor y boxplots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPJzUQGQC864TJGQktt03JVEXVM8gQPQ
"""

from sklearn import datasets
import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('datos_2021.csv',na_values=' ')
df

print(df.shape)
print(df.columns)
obj_columns = df.select_dtypes(include=np.object).columns.tolist()
df[obj_columns] = df[obj_columns].astype('string')
df['Estación SIMAJ'] = df['Estación SIMAJ'].str.lower()
print(df.info())

print(df.describe())

print(df.isna().sum()/len(df)*100)

df_nuevo = df.loc[:,['Hora','O3','CO','TMP']]
df_nuevo

df_nuevo.corr()

fig = plt.figure(figsize=(15,10))
sns.heatmap(df_nuevo.corr(),annot=True, cmap = 'BuGn')
plt.show()

fig = plt.figure(figsize=(10,4))
sns.boxplot(data=df_nuevo[['TMP']], orient="h",color='r')
plt.show()

fig = plt.figure(figsize=(10,4))
sns.boxplot(data=df_nuevo[['Hora']], orient="h")
plt.show()

fig = plt.figure(figsize=(10,4))
sns.boxplot(data=df_nuevo[['O3']], orient="h",color='g')
plt.show()

fig = plt.figure(figsize=(10,4))
sns.boxplot(data=df_nuevo[['CO']], orient="h",color='purple')
plt.show()