# -*- coding: utf-8 -*-
"""Obtención de estadisticas descriptivas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvTVMa2lPTHlsRCQf5gwc4hUcpzCRWaW

# Actividad Evaluable: Obtención de estadisticas descriptivas

En esta actividad trabajaras con el conjunto de datos asignado para el reto.
"""

# imports
from sklearn import datasets
import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt
import seaborn as sns

"""Importamos las librerías necesarias para poder correr el programa y también añadimos el archivo csv con los datos a trabajar"""

# importar tabla
df = pd.read_csv('datos_2021.csv',na_values=' ')

"""***1. Carga los datos usando tu lector de csv o con pandas.***

Importamos el archivo csv usando pandas y generamos la tabla de datos
"""

df

"""***2. Verifica la cantidad de datos que tienes, las variables que contiene cada vector de datos e identifica el tipo de variables.***

"""

print(df.shape)
print(df.columns)
obj_columns = df.select_dtypes(include=np.object).columns.tolist()
df[obj_columns] = df[obj_columns].astype('string')
print(df.info())

print(df.describe())

#Cantidad de informacion ausente
print(df.isna().sum()/len(df)*100)

df_nuevo = df.loc[:,['Hora','O3','CO','TMP']]
df_nuevo



